proof_of_concept_3_dof_legs:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  lf1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rf1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rh1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lh1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lf2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rf2_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rh2_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lh2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lf3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rf3_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rh3_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lh3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh3
    pid: {p: 100.0, i: 0.01, d: 10.0}
